/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import models.Appointment;
import utilities.DBAccess;

/**
 *
 * @author Ecchi Powa
 */
public class CalendarWindow extends ModuleWindow {

    /**
     * Creates new form Calendar
     */
    
    private ArrayList<Appointment> appointmentX;
    
    
    public CalendarWindow() {
        initComponents();
        appointmentX = new ArrayList<>();
        appointmentX = DBAccess.getAppointmentData("");
        
        calendarDaySelector.addItemListener(new ItemListener(){
            
            private int selected = 0;
            
            public void itemStateChanged(ItemEvent e) {
                if(calendarDaySelector.getSelectedIndex() != 0 && calendarDaySelector.getSelectedIndex() != selected){
                    selected = Integer.parseInt(calendarDaySelector.getSelectedItem().toString());
                    try{
                        for(int i = 0; i < selected; i++){
                            calendarHolder.add(new CalendarDay(appointmentX.get(i).getAppointmentDate()));
                        }   
                    }catch(Exception ex){
                        System.out.println("Item State Error: "+e);
                    }
                }
            }
        });
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarAppointment = new javax.swing.JPanel();
        calendarDaySelector = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        calendarHolder = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(686, 546));

        calendarAppointment.setBorder(javax.swing.BorderFactory.createTitledBorder("Appointment Viewer"));

        calendarDaySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Days Viewed", "1", "2", "3", "4", "5", "6", "7" }));

        jButton1.setText("Add New Appointment");

        javax.swing.GroupLayout calendarAppointmentLayout = new javax.swing.GroupLayout(calendarAppointment);
        calendarAppointment.setLayout(calendarAppointmentLayout);
        calendarAppointmentLayout.setHorizontalGroup(
            calendarAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarAppointmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(calendarDaySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        calendarAppointmentLayout.setVerticalGroup(
            calendarAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calendarAppointmentLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(calendarAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendarDaySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        calendarHolder.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        calendarHolder.setPreferredSize(new java.awt.Dimension(4, 417));
        calendarHolder.setLayout(new javax.swing.BoxLayout(calendarHolder, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendarHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(calendarAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calendarHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendarAppointment;
    private javax.swing.JComboBox calendarDaySelector;
    private javax.swing.JPanel calendarHolder;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
