/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toothbytes.ui.components;

import java.awt.Dialog;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JDialog;
import toothbytes.database.DBAccess;
import toothbytes.model.Appointment;
import toothbytes.model.RecordsX;

/**
 *
 * @author Ecchi Powa
 */
public class PaymentSchedule extends javax.swing.JPanel {

    /**
     * Creates new form PaymentSchedule
     */
        
    private Appointment appointment;
    private ArrayList<RecordsX> recordsX;
    
    public PaymentSchedule(Appointment appointment) {
        initComponents();
        this.appointment = appointment;
        recordsX = DBAccess.getRecordsData(appointment.getPatientID());
        setInformation();
    }
    
    private void setInformation(){
        DecimalFormat df = new DecimalFormat("#,###.00");
        NameLabel.setText(DBAccess.getPatientName(appointment.getPatientID()));
        DateLabel.setText(appointment.getAppointmentDate());
        TimeLabel.setText(appointment.getAppointmentTime());
        AmountLabel.setText("P " + String.valueOf(df.format(totalBalance())));
    }
    
    private double totalBalance(){
        double total = 0;
        
        for(int i = 0; i < recordsX.size(); i++){
            total = total + recordsX.get(i).getBalance();
        }
        
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        NameLabel.setText("Name");

        TimeLabel.setText("Time");

        AmountLabel.setText("Remaining Balance");

        DateLabel.setText("Date");

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TimeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(TimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                JDialog miniBill = new JDialog();
                MiniBilling miniBilling = new MiniBilling(miniBill, appointment.getPatientID());
                miniBill.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
                miniBill.setSize(miniBilling.getPreferredSize());
                miniBill.add(miniBilling);
                miniBill.pack();
                miniBill.setVisible(true);
                miniBill.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            }
        });
        
        /*java.awt.EventQueue.invokeLater(new Runnable() {

                    public void run() {
                        JDialog ctb = new JDialog();
                        PersonalInformation pi = new PersonalInformation(ctb);
                        ctb.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
                        System.out.println(pi.isVisible());
                        ctb.setSize(pi.getPreferredSize());
                        ctb.add(pi);
                        ctb.pack();
                        ctb.setVisible(true);
                        ctb.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                    }
                });*/
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
