/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package toothbytes.ui.components;

import java.text.DecimalFormat;
import java.util.ArrayList;
import toothbytes.database.DBAccess;
import toothbytes.model.Appointment;
import toothbytes.model.RecordsX;

/**
 *
 * @author Ecchi Powa
 */
public class PaymentSchedule extends javax.swing.JPanel {

    /**
     * Creates new form PaymentSchedule
     */
        
    private Appointment appointment;
    private ArrayList<RecordsX> recordsX;
    
    public PaymentSchedule(Appointment appointment) {
        initComponents();
        this.appointment = appointment;
        recordsX = DBAccess.getRecordsData(appointment.getPatientID());
        setInformation();
    }
    
    private void setInformation(){
        DecimalFormat df = new DecimalFormat("#,###.00");
        NameLabel.setText(DBAccess.getPatientName(appointment.getPatientID()));
        DateLabel.setText(appointment.getAppointmentDate());
        TimeLabel.setText(appointment.getAppointmentTime());
        AmountLabel.setText("P " + String.valueOf(df.format(totalBalance())));
    }
    
    private double totalBalance(){
        double total = 0;
        
        for(int i = 0; i < recordsX.size(); i++){
            total = total + recordsX.get(i).getBalance();
        }
        
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        AmountLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();

        NameLabel.setText("Name");

        TimeLabel.setText("Time");

        AmountLabel.setText("Remaining Balance");

        DateLabel.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TimeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel)
                            .addComponent(AmountLabel))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateLabel)
                    .addComponent(TimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmountLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel TimeLabel;
    // End of variables declaration//GEN-END:variables
}
